"MD007":
  "indent": 4
"MD038": false
"MD033": false # inline html
"MD013": false # line-length
"MD034": false # bare links
"MD040": false # fenced code blocks should have language selected
"MD053": false # do not remove mkdocs materials footnotes
"MD046": false # do not check code fence vs indent style
