authors:
  rdodin:
    name: Roman Dodin
    description: SR Linux PLM
    avatar: https://avatars.githubusercontent.com/u/5679861

  jbemmel:
    name: Jeroen van Bemmel
    description: Webscale Architect
    avatar: https://avatars.githubusercontent.com/u/2031627

  sogawa:
    name: Satoshi Ogawa
    description: Webscale Solutions Architect
    avatar: https://avatars.githubusercontent.com/u/2031627

  azyablov:
    name: Anton Zyablov
    description: Lead Solution Architect
    avatar: https://avatars.githubusercontent.com/u/22647209

  amitk:
    name: Amit K
    description: Consulting Engineer
    avatar: https://gitlab.com/rdodin/pics/-/wikis/uploads/6e635cf946b54f33d7d314143ad4144d/image.png

  mau:
    name: Mauricio Rojas
    description: Network Automation Consulting Engineer
    avatar: https://avatars.githubusercontent.com/u/69992138

  wdesmedt:
    name: Walter De Smedt
    description: Consulting Engineer
    avatar: https://avatars.githubusercontent.com/u/13483865

  michelredondo:
    name: Míchel Redondo
    description: Solution Architect
    avatar: https://avatars.githubusercontent.com/u/130749542

  ejames:
    name: Erwan James
    description: SR Linux/FSS PLM
    avatar: https://pbs.twimg.com/profile_images/832455171942739968/QeTHPwVv_400x400.jpg

  sabdulra:
    name: Saju Salahudeen
    description: Principal Consulting Engineer
    avatar: https://gitlab.com/rdodin/pics/-/wikis/uploads/f2ddd9f71671832defa9c358e00de544/image.png

  reda:
    name: Reda Laichi
    description: Principal Consulting Engineer
    avatar: https://gitlab.com/rdodin/pics/-/wikis/uploads/5bf3dab5d3fb65077ed5658d32a03300/image.png
